
services:
  rust-app:
    build: ./app
    tty: true
    volumes:
      - ./app:/app
      - ./.aws:/root/.aws
    working_dir: /app
    ports:
      - "8080:8080"
      - "8081:8081"
      - "9000:9000"